# Generated by Django 2.2 on 2020-10-21 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=20)),
                ('habitaciones', models.IntegerField(max_length=20)),
                ('dormitorios', models.IntegerField(max_length=20)),
                ('baños', models.IntegerField(max_length=20)),
                ('imagenes', models.ImageField(blank=True, upload_to='fotos/')),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=20)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inmobibliaria.Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=20)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inmobibliaria.Propiedad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inmobibliaria.Usuario')),
            ],
        ),
    ]
