# Generated by Django 2.2 on 2020-10-30 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
                ('barrio', models.CharField(max_length=30)),
                ('calle', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('Departamento', 'Departamento'), ('Casa', 'Casa'), ('Garaje', 'Garaje'), ('Oficina', 'Oficina')], default='Casa', max_length=12)),
                ('estado', models.CharField(choices=[('Alquiler', 'En Alquiler'), ('Venta', 'En Venta')], default='Venta', max_length=8)),
                ('habitaciones', models.IntegerField()),
                ('baños', models.IntegerField()),
                ('tamaño', models.IntegerField()),
                ('imagenes', models.ImageField(blank=True, upload_to='fotos/')),
                ('descripcion', models.CharField(max_length=200)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inmobibliaria.Ubicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=200)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inmobibliaria.Propiedad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
