# Generated by Django 2.2 on 2020-10-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inmobibliaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='precio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
