# Generated by Django 2.2 on 2020-10-30 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inmobibliaria', '0002_auto_20201030_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='dormitorios',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consulta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
