# Generated by Django 2.2 on 2020-11-12 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inmobibliaria', '0002_propiedad_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='imagenes',
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(null=True, upload_to='fotos/')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inmobibliaria.Propiedad')),
            ],
        ),
    ]
