# Generated by Django 2.2 on 2020-10-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inmobibliaria', '0003_auto_20201030_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='estado',
            field=models.CharField(choices=[('Alquiler', 'En Alquiler'), ('Venta', 'En Venta')], default='Venta', max_length=12),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipo',
            field=models.CharField(choices=[('Departamento', 'Departamento'), ('Casa', 'Casa'), ('Garaje', 'Garaje'), ('Oficina', 'Oficina')], default='Casa', max_length=8),
        ),
    ]
