# Generated by Django 2.2 on 2020-11-13 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inmobibliaria', '0004_auto_20201113_0323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ubicacion',
            old_name='provinia',
            new_name='provincia',
        ),
    ]
