# Generated by Django 2.2 on 2020-10-30 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inmobibliaria', '0004_auto_20201030_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
                ('barrio', models.CharField(max_length=30)),
                ('calle', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tamaño',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inmobibliaria.Ubicacion'),
        ),
    ]
