# Generated by Django 2.2 on 2020-11-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inmobibliaria', '0006_auto_20201113_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='estado',
            field=models.IntegerField(choices=[(0, 'En Alquiler'), (1, 'En Venta')], default=0),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Departamento'), (1, 'Casa'), (2, 'Garaje'), (3, 'Oficina')], default=0),
        ),
    ]
