# Generated by Django 2.2 on 2020-11-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inmobibliaria', '0008_auto_20201113_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='tipo',
            field=models.CharField(choices=[('Departamento', 'Departamento'), ('Casa', 'Casa'), ('Garaje', 'Garaje'), ('Oficina', 'Oficina')], max_length=12),
        ),
    ]
