# Generated by Django 2.2 on 2020-11-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inmobibliaria', '0009_auto_20201113_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacion',
            name='barrio',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='numero',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='barrio',
            field=models.CharField(default='A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedad',
            name='calle',
            field=models.CharField(default='a', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedad',
            name='numero',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
