# Generated by Django 2.2 on 2020-11-18 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inmobibliaria', '0010_auto_20201118_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacion',
            name='ciudad',
        ),
    ]
