# Generated by Django 2.2 on 2020-11-19 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inmobibliaria', '0013_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
