# Generated by Django 2.2 on 2020-11-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inmobibliaria', '0015_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
