# Generated by Django 2.2 on 2020-11-19 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inmobibliaria', '0017_auto_20201119_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Inmobibliaria.Propiedad'),
        ),
    ]
