# Generated by Django 2.2 on 2020-11-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inmobibliaria', '0021_propiedad_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='estado',
            field=models.CharField(choices=[('Alquiler', 'En Alquiler'), ('Venta', 'En Venta')], max_length=8),
        ),
    ]
